# Generated by Django 4.1.2 on 2022-10-11 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PMSapp', '0002_entries_rename_is_intern_user_is_employee_manager_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entries',
            name='employee_id',
            field=models.CharField(default=1, max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='entries',
            name='Email_id',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
