# Generated by Django 4.1.2 on 2022-10-16 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PMSapp', '0004_employee_progress_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='name',
            field=models.CharField(default='Anonymous', max_length=100),
        ),
    ]
