# Generated by Django 4.1.2 on 2022-10-31 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PMSapp', '0008_remove_comments_name_remove_comments_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='review',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='PMSapp.reviews'),
        ),
    ]
