# Generated by Django 4.1.2 on 2022-11-05 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PMSapp', '0010_comments_receiver_name_comments_sender_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='freezing_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reviews',
            name='is_frozen',
            field=models.BooleanField(default=False),
        ),
    ]
