# Generated by Django 4.1.2 on 2022-11-06 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PMSapp', '0013_self_appraisals_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='assigned_manager',
            field=models.ForeignKey(default='Not Alloted', on_delete=django.db.models.deletion.CASCADE, to='PMSapp.manager'),
        ),
    ]
