# Generated by Django 4.1.2 on 2022-11-06 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PMSapp', '0015_alter_employee_assigned_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='assigned_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='PMSapp.manager'),
        ),
    ]
