# Generated by Django 4.1.2 on 2022-11-09 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PMSapp', '0016_alter_employee_assigned_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='receiver_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='comments',
            name='sender_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='employee',
            name='assigned_manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PMSapp.manager'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
